/**
 * Commit the icon bodies the browse pages draw (G3 §6).
 *
 *   node scripts/build-icons.mjs
 *
 * Reads the wanted ids out of `lib/icons/registry.ts`, pulls each body
 * from the installed `@iconify-json/*` packages, normalises it, and writes
 * `lib/icons/icon-bodies.generated.ts`.
 *
 * **Nothing fetches anything, here or at request time.** `@iconify/react`
 * would have been three lines, but it asks `api.iconify.design` for icon
 * data at runtime by default, is `"use client"`, and renders an empty
 * span until it mounts — a third-party host on the request path (which is
 * why `images.remotePatterns` is empty), a client bundle for a static
 * shape, and a visible pop. `unplugin-icons` wants webpack and this app
 * builds with Turbopack. So the output is committed, the same stance as
 * `build-chef-avatars.mjs`, and the `@iconify-json` packages stay
 * devDependencies that never reach a browser.
 *
 * Re-run it after editing the registry; `icon-registry.spec.ts` fails the
 * build if the two disagree, so a forgotten run cannot ship.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { getIconData, iconToSVG } from "@iconify/utils";

const require = createRequire(import.meta.url);
const HERE = dirname(fileURLToPath(import.meta.url));
const REGISTRY = join(HERE, "..", "lib", "icons", "registry.ts");
const OUT = join(HERE, "..", "lib", "icons", "icon-bodies.generated.ts");

/**
 * One stroke weight for the whole set.
 *
 * Lucide draws at 2 and hugeicons at 1.5, so a chip row mixing the two
 * reads as two different icon sets sitting next to each other — which is
 * exactly the thing §6 is trying to avoid. 1.5 matches `CraftIcon`.
 */
const STROKE_WIDTH = "1.5";

/**
 * The ids are read out of the registry rather than repeated here.
 *
 * A regex over the file rather than an import, because this is Node 20
 * and the registry is TypeScript. That is only safe because the parity
 * spec re-reads both files and fails the build on any difference — if
 * this extraction ever misses an id, a test says so rather than a tile
 * silently falling back.
 */
function wantedIds() {
  const source = readFileSync(REGISTRY, "utf8");
  const ids = new Set();
  for (const match of source.matchAll(/id:\s*"([a-z0-9-]+:[a-z0-9-]+)"/g)) {
    ids.add(match[1]);
  }
  return [...ids];
}

const SETS = new Map();
function iconSet(prefix) {
  if (!SETS.has(prefix)) {
    SETS.set(prefix, require(`@iconify-json/${prefix}/icons.json`));
  }
  return SETS.get(prefix);
}

/**
 * Keep the shape and drop everything else.
 *
 * A hardcoded colour would ignore the `color` the tile sets, and an
 * `id`/`class` would collide the moment two icons render on one page.
 * `currentColor` is the whole contract with `Icon.tsx`.
 */
function normalise(body) {
  return body
    .replace(/stroke-width="[^"]*"/g, `stroke-width="${STROKE_WIDTH}"`)
    .replace(/(stroke|fill)="#[0-9a-fA-F]{3,8}"/g, '$1="currentColor"')
    .replace(/\s(id|class)="[^"]*"/g, "");
}

const bodies = {};
const missing = [];

for (const id of wantedIds().sort()) {
  const [prefix, name] = id.split(":");
  // The hand-drawn half is React, not an SVG body — `CraftIcon` draws it.
  if (prefix === "craft") continue;

  let data = null;
  try {
    data = getIconData(iconSet(prefix), name);
  } catch {
    data = null;
  }
  if (!data) {
    missing.push(id);
    continue;
  }

  const rendered = iconToSVG(data, { height: "24" });
  bodies[id] = {
    body: normalise(rendered.body),
    viewBox: rendered.attributes.viewBox,
  };
}

if (missing.length > 0) {
  console.error(`Not in any installed set:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}

const entries = Object.entries(bodies)
  .map(
    ([id, icon]) =>
      `  ${JSON.stringify(id)}: {\n    viewBox: ${JSON.stringify(icon.viewBox)},\n    body: ${JSON.stringify(icon.body)},\n  },`,
  )
  .join("\n");

writeFileSync(
  OUT,
  `// Generated by scripts/build-icons.mjs — do not edit by hand.
// Sources: @iconify-json/{lucide,lucide-lab} (ISC), @iconify-json/hugeicons (MIT).
// No attribution is owed for any of these licences; nothing is fetched at
// build or request time. Re-run the script after editing lib/icons/registry.ts.

export interface IconBody {
  viewBox: string;
  body: string;
}

export const ICON_BODIES: Record<string, IconBody> = {
${entries}
};
`,
  "utf8",
);

console.log(`${Object.keys(bodies).length} icons → lib/icons/icon-bodies.generated.ts`);
