#!/bin/sh
# Regenerates the cfg.cssEntry stylesheet the converter appends into
# _ds_bundle.css. Order mirrors app/layout.tsx: tokens -> extend -> globals.
# Re-run before every design-sync build (styles/*.css are the source of truth).
set -e
cd "$(dirname "$0")/.."
{
  echo "/* generated by .design-sync/build-css.sh - do not edit */"
  cat styles/tokens.css styles/tokens.extend.css styles/globals.css
  if [ -f .design-sync/fonts/fonts.css ]; then cat .design-sync/fonts/fonts.css; fi
} > .design-sync/ds-styles.css
